version: '3'
services:
  senaite:
      image: mekomsolutions/senaite:latest
      environment:
        - SITE=senaite
        - ADMIN_USER=admin
        - ADMIN_PASSWORD=password
      ports:
      - "8080:8080"

      volumes:
      - ./data:/data/importdata/senaite
