name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v1 
        with:
          username: mekomsolutions
          password: ${{ secrets.DOCKER_HUB_REGISTRY_PASSWORD }}
      - 
        name: Get commit id
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      -
        name: Build and push
        uses: docker/build-push-action@v2
        env: 
          SERVICE: senaite
        with:
          platforms: linux/amd64,linux/arm64
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: mekomsolutions/${{ env.SERVICE }}:latest,mekomsolutions/${{ env.SERVICE }}:${{ steps.vars.outputs.sha_short }}
